from __future__ import annotations

"""Diagnostic helpers for replay transaction-boundary and first-mismatch audits."""

import hashlib
import json
from collections import Counter, defaultdict
from typing import Any, Dict, Iterable, List, Optional

from .state_hash import canonical_state_payload, runtime_state_payload

# Rows known to carry or imply graph/runtime mutation. Some are regenerated by
# causal APIs; this list exists to make ignored mutation assumptions visible.
POTENTIALLY_MUTATING_ROW_TYPES = {
    "event_written", "outcome_written", "state_hash", "step_end",
    "episode_opened", "episode_closed", "extraction_ingested",
    "concept_promoted", "reinforced", "candidate_variant_integrated",
    "candidate_reinforcement_integrated", "episode_event_detached",
    "episode_transition_event_reassigned", "pre_answer_investigation_created",
    "action_rationale_recorded", "investigation_workspace_created",
    "provisional_outcome_written", "candidate_cached",
    "candidate_pedigree_evaluated", "artifact_assigned_to_locality",
    "locality_region_proposed", "locality_region_state_changed",
    "developmental_hypothesis_synthesized", "recurrent_episode_collated",
    "hypothesis_locality_designated", "governance_proposal_created",
    "governance_proposal_promotion_evaluated", "governance_promotion_evaluated",
    "collation_period_started", "collation_period_completed",
    "collation_period_complete", "candidate_utility_updated",
    "successful_action_anchor_reinforced", "successful_anchor_regression_observed",
}

REDUCER_HANDLED_TYPES = {
    "event_written", "outcome_written", "developmental_event_written", "state_hash",
    "pre_answer_investigation_created", "action_rationale_recorded",
    "investigation_workspace_created", "provisional_outcome_written",
    "candidate_cached", "candidate_pedigree_evaluated",
    "artifact_assigned_to_locality", "locality_region_proposed",
    "locality_region_state_changed", "developmental_hypothesis_synthesized",
    "recurrent_episode_collated", "hypothesis_locality_designated",
    "governance_proposal_created", "governance_proposal_promotion_evaluated",
    "governance_promotion_evaluated", "collation_period_started",
    "collation_period_completed", "collation_period_complete",
    "candidate_utility_updated", "successful_action_anchor_reinforced",
    "successful_anchor_regression_observed",
}


def _stable(obj: Any) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def _hash(obj: Any) -> str:
    return hashlib.sha256(_stable(obj).encode("utf-8")).hexdigest()


def duplicate_canonical_signatures(payload: Dict[str, Any]) -> List[Dict[str, Any]]:
    groups: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for node in payload.get("nodes", []) or []:
        sig = _stable({"type": node.get("type"), "data": node.get("data") or {}})
        groups[sig].append(node)
    return [
        {"signature": sig, "count": len(nodes), "keys": [n.get("key") for n in nodes]}
        for sig, nodes in groups.items() if len(nodes) > 1
    ]


def canonical_payload_diff(expected: Optional[Dict[str, Any]], actual: Dict[str, Any], limit: int = 8) -> Dict[str, Any]:
    if not expected:
        return {"available": False, "reason": "expected diagnostic_canonical_state was not recorded"}
    exp_nodes = {_stable(n): n for n in expected.get("nodes", []) or []}
    act_nodes = {_stable(n): n for n in actual.get("nodes", []) or []}
    exp_edges = {_stable(e): e for e in expected.get("edges", []) or []}
    act_edges = {_stable(e): e for e in actual.get("edges", []) or []}
    missing_nodes = [exp_nodes[k] for k in sorted(exp_nodes.keys() - act_nodes.keys())[:limit]]
    extra_nodes = [act_nodes[k] for k in sorted(act_nodes.keys() - exp_nodes.keys())[:limit]]
    missing_edges = [exp_edges[k] for k in sorted(exp_edges.keys() - act_edges.keys())[:limit]]
    extra_edges = [act_edges[k] for k in sorted(act_edges.keys() - exp_edges.keys())[:limit]]
    return {
        "available": True,
        "expected_payload_hash": _hash(expected),
        "actual_payload_hash": _hash(actual),
        "expected_node_count": len(expected.get("nodes", []) or []),
        "actual_node_count": len(actual.get("nodes", []) or []),
        "expected_edge_count": len(expected.get("edges", []) or []),
        "actual_edge_count": len(actual.get("edges", []) or []),
        "missing_nodes": missing_nodes,
        "extra_nodes": extra_nodes,
        "missing_edges": missing_edges,
        "extra_edges": extra_edges,
        "expected_duplicate_signatures": duplicate_canonical_signatures(expected)[:limit],
        "actual_duplicate_signatures": duplicate_canonical_signatures(actual)[:limit],
    }


def boundary_audit(rows: Iterable[Dict[str, Any]]) -> Dict[str, Any]:
    rows = list(rows)
    hash_rows: List[Dict[str, Any]] = []
    step_counts: Counter[int] = Counter()
    last_hash_index = -1
    current_boundary = 0
    per_boundary: Dict[int, Dict[str, Any]] = defaultdict(lambda: {
        "row_types_before_hash": [], "ignored_potential_mutations": [], "row_indices": []
    })
    for idx, row in enumerate(rows):
        typ = str(row.get("type") or "")
        data = row.get("data") or {}
        if typ == "state_hash":
            step = int(data.get("step", 0) or 0)
            step_counts[step] += 1
            hash_rows.append({"row_index": idx, "step": step, "hash": data.get("hash"),
                              "runtime_state": data.get("runtime_state") or {},
                              "diagnostic_config": data.get("diagnostic_config") or {}})
            per_boundary[step]["hash_row_index"] = idx
            per_boundary[step]["recorded_runtime_state"] = data.get("runtime_state") or {}
            per_boundary[step]["diagnostic_config"] = data.get("diagnostic_config") or {}
            current_boundary = step
            last_hash_index = idx
            continue
        target = current_boundary + 1
        per_boundary[target]["row_types_before_hash"].append(typ)
        per_boundary[target]["row_indices"].append(idx)
        if typ in POTENTIALLY_MUTATING_ROW_TYPES and typ not in REDUCER_HANDLED_TYPES:
            per_boundary[target]["ignored_potential_mutations"].append({"row_index": idx, "type": typ, "data_step": data.get("step")})
    post_hash_rows = [
        {"row_index": idx, "type": str(row.get("type") or ""), "data_step": (row.get("data") or {}).get("step")}
        for idx, row in enumerate(rows[last_hash_index + 1:], start=last_hash_index + 1)
    ] if last_hash_index >= 0 else []
    return {
        "total_rows": len(rows),
        "state_hash_row_count": len(hash_rows),
        "unique_state_hash_steps": len(step_counts),
        "state_hash_sequence": hash_rows,
        "duplicate_step_numbers": {str(k): v for k, v in step_counts.items() if v > 1},
        "non_monotonic_or_restarted_steps": [
            {"previous": hash_rows[i-1]["step"], "current": hash_rows[i]["step"], "row_index": hash_rows[i]["row_index"]}
            for i in range(1, len(hash_rows)) if hash_rows[i]["step"] <= hash_rows[i-1]["step"]
        ],
        "post_final_hash_rows": post_hash_rows,
        "post_final_hash_potential_mutations": [r for r in post_hash_rows if r["type"] in POTENTIALLY_MUTATING_ROW_TYPES],
        "boundaries": {str(k): v for k, v in sorted(per_boundary.items())},
    }


def replay_precondition_snapshot(engine: Any) -> Dict[str, Any]:
    return {
        "runtime_state": runtime_state_payload(engine),
        "config": {
            "enable_decay": bool(getattr(engine, "enable_decay", True)),
            "ablate_governance": bool(getattr(engine, "ablate_governance", False)),
            "candidate_cache_ttl_steps": int(getattr(engine, "candidate_cache_ttl_steps", 0)),
            "max_candidate_cache": int(getattr(engine, "max_candidate_cache", 0)),
            "protected_candidate_ttl_steps": int(getattr(engine, "protected_candidate_ttl_steps", 0)),
            "auto_collation_interval_steps": getattr(engine, "auto_collation_interval_steps", None),
        },
        "current_episode_id": getattr(engine, "_current_episode_id", None),
    }
